name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ASSET_HOST: https://d22jnhtfnuyr7y.cloudfront.net
  SITE_HOST: https://author-p31359-e533775.adobeaemcloud.com
  CONFIG_NAME: test-site
  CONFIG_PATH: $SITE_HOST/conf/${CONFIG_NAME}/sling:configs/com.adobe.cq.wcm.core.components.config.HtmlPageItemsConfig/jcr:content


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Calculate distribution hash
        run: echo "DIRHASH=$(tar -b20 -cf - ./dist | shasum | awk '{print $1}')" >> $GITHUB_ENV
      - name: Echo hash
        run: echo "${{ env.DIRHASH }}"
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'
          SOURCE_DIR: 'dist'
          DEST_DIR: "${{ env.DIRHASH }}"

      - name: Echo curl CONFIG_PATH=${SITEHOST}/conf/${CONFIG_NAME}/sling:configs/com.adobe.cq.wcm.core.components.config.HtmlPageItemsConfig/jcr:contentrun: | 
        run: |
          echo curl --url "${{ env.CONFIG_PATH }}" \
          --header 'authorization: Bearer ${{ secrets.AEM_BEARER_TOKEN }}' \
          --data-urlencode 'prefixPath=$ASSET_HOST/${{ env.DIRHASH }}''
      - name: Update HTML page item prefixPath        
        run: |
          curl --url "${{ env.CONFIG_PATH }}" \ 
          --header 'authorization: Bearer ${{ secrets.AEM_BEARER_TOKEN }}' \
          --data-urlencode 'prefixPath=$ASSET_HOST/${{ env.DIRHASH }}''
